package org.moashraf.sayva.languagepack

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.floatOrNull
import kotlinx.serialization.json.int
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Parses a distributed pack `manifest.json` (generated by
 * `ml/scripts/generate_pack.py`) into a [LanguagePack].
 *
 * Uses `kotlinx.serialization`'s low-level `JsonElement` tree rather than
 * `@Serializable` data classes because the manifest is a stable-but-evolving
 * shape and we want field-level error messages when a pack drifts from the
 * schema. Errors point at exactly which field failed and inside which pack.
 */
object PackManifestParser {

    private val json = Json { ignoreUnknownKeys = true }

    /**
     * Parse a manifest JSON string.
     *
     * @throws PackManifestException with a message that names the pack and
     *   the missing/malformed field.
     */
    fun parse(jsonText: String): LanguagePack {
        val root = runCatching { json.parseToJsonElement(jsonText).jsonObject }
            .getOrElse { throw PackManifestException("Root JSON is not an object", it) }

        val packCode = root.string("recognitionCode")
        try {
            val schemaVersion = root.int("schemaVersion")
            val displayName = root.stringMap("displayName")
            val version = root.string("version")
            val minAppVersion = root.int("minAppVersion")
            val bundled = root["bundled"]?.jsonPrimitive?.contentOrNull?.equals("true", ignoreCase = true)
                ?: (root["bundled"]?.jsonPrimitive?.contentOrNull?.toBooleanStrictOrNull() ?: false)

            val models = root.array("models").map { parseModel(it.jsonObject) }
            if (models.isEmpty()) fail(packCode, "'models' must have at least one entry")

            val supportedOutputs = root.array("supportedOutputs")
                .map { it.jsonPrimitive.content }

            val statusRaw = root["outputLanguageStatus"]?.jsonObject
                ?: fail(packCode, "missing 'outputLanguageStatus'")
            val outputLanguageStatus = statusRaw.mapValues { (_, v) ->
                OutputLanguageStatus.fromWireValue(v.jsonPrimitive.content)
            }

            val defaultOutputLanguage = root.string("defaultOutputLanguage")
            if (defaultOutputLanguage !in supportedOutputs) {
                fail(packCode, "defaultOutputLanguage '$defaultOutputLanguage' not in supportedOutputs")
            }

            val outputLabels = parseOutputLabels(root)

            val ttsLocaleByOutput = root.stringMap("ttsLocaleByOutput")

            val ppRaw = root["postProcessing"]?.jsonObject
                ?: fail(packCode, "missing 'postProcessing'")
            val postProcessing = PostProcessingRules(
                spellOutBlankTimeoutMs = ppRaw.int("spellOutBlankTimeoutMs"),
                sentenceAssemblyRuleset = ppRaw.string("sentenceAssemblyRuleset"),
                capitalization = ppRaw.string("capitalization"),
            )

            return LanguagePack(
                schemaVersion = schemaVersion,
                recognitionCode = packCode,
                displayName = displayName,
                version = version,
                minAppVersion = minAppVersion,
                bundled = bundled,
                models = models,
                supportedOutputs = supportedOutputs,
                outputLanguageStatus = outputLanguageStatus,
                defaultOutputLanguage = defaultOutputLanguage,
                outputLabels = outputLabels,
                ttsLocaleByOutput = ttsLocaleByOutput,
                postProcessing = postProcessing,
            )
        } catch (e: PackManifestException) {
            throw e
        } catch (e: Throwable) {
            throw PackManifestException("Pack '$packCode' manifest parse error: ${e.message}", e)
        }
    }

    private fun parseModel(obj: JsonObject): PackModel {
        val id = obj.string("id")
        val role = obj.string("role")
        val architecture = obj.string("architecture")
        val file = obj.string("modelFile")

        val runtimeObj = obj["runtime"]?.jsonObject
            ?: error("model '$id' missing 'runtime'")
        val runtimeType = runtimeObj.string("type")

        val inferenceStrategy = obj.string("inferenceStrategy")

        val inputObj = obj["input"]?.jsonObject
            ?: error("model '$id' missing 'input'")
        val input = ModelInputSpec(
            shape = inputObj.array("shape").map { it.jsonPrimitive.int },
            preprocessing = inputObj.string("preprocessing"),
            maxHands = inputObj.int("maxHands"),
            sequenceLength = inputObj["sequenceLength"]?.jsonPrimitive?.intOrNull,
        )
        require(input.maxHands in 1..2) {
            "model '$id' maxHands must be 1 or 2, got ${input.maxHands}"
        }

        val outputObj = obj["output"]?.jsonObject
            ?: error("model '$id' missing 'output'")
        val output = ModelOutputSpec(
            shape = outputObj.array("shape").map { it.jsonPrimitive.int },
            postprocessing = outputObj.string("postprocessing"),
        )

        val thresholdsObj = obj["confidenceThresholds"]?.jsonObject
            ?: error("model '$id' missing 'confidenceThresholds'")
        val thresholds = ConfidenceThresholds(
            show = thresholdsObj["show"]?.jsonPrimitive?.floatOrNull
                ?: error("model '$id' confidenceThresholds.show missing or not a number"),
            caution = thresholdsObj["caution"]?.jsonPrimitive?.floatOrNull
                ?: error("model '$id' confidenceThresholds.caution missing or not a number"),
        )

        val vocabObj = obj["vocabulary"]?.jsonObject
            ?: error("model '$id' missing 'vocabulary'")
        val vocab = SignVocabulary(
            version = vocabObj.int("version"),
            signs = vocabObj.array("signs").mapIndexed { i, el ->
                val s = el.jsonObject
                VocabSign(
                    index = i,
                    id = s.string("id"),
                    tags = s.array("tags").map { it.jsonPrimitive.content },
                )
            },
        )

        // Sanity: model output classes must equal vocab size.
        val outClasses = output.shape.lastOrNull()
            ?: error("model '$id' output shape empty")
        require(outClasses == vocab.size) {
            "model '$id' declares $outClasses output classes but vocabulary has ${vocab.size} signs"
        }

        return PackModel(
            id = id,
            role = role,
            architecture = architecture,
            modelFile = file,
            runtimeType = runtimeType,
            inferenceStrategy = inferenceStrategy,
            input = input,
            output = output,
            confidenceThresholds = thresholds,
            vocabulary = vocab,
        )
    }

    /**
     * Structure of `outputLabels` in the JSON:
     * `{ outputCode: { modelId: { signId: labelOrNull, ... } } }`
     * We keep it exactly like that in memory — a triple-nested map.
     */
    private fun parseOutputLabels(
        root: JsonObject,
    ): Map<String, Map<String, Map<String, String?>>> {
        val raw = root["outputLabels"]?.jsonObject ?: return emptyMap()
        return raw.mapValues { (_, perLangEl) ->
            perLangEl.jsonObject.mapValues { (_, perModelEl) ->
                perModelEl.jsonObject.mapValues { (_, entryEl) ->
                    entryEl.jsonPrimitive.contentOrNull
                }
            }
        }
    }

    private fun JsonObject.string(key: String): String =
        this[key]?.jsonPrimitive?.contentOrNull
            ?: error("missing string '$key'")

    private fun JsonObject.int(key: String): Int =
        this[key]?.jsonPrimitive?.intOrNull
            ?: error("missing int '$key'")

    private fun JsonObject.array(key: String): JsonArray =
        this[key]?.jsonArray
            ?: error("missing array '$key'")

    private fun JsonObject.stringMap(key: String): Map<String, String> {
        val obj = this[key]?.jsonObject ?: error("missing object '$key'")
        return obj.mapValues { (_, v) -> v.jsonPrimitive.content }
    }

    // Float unused right now but kept for future numeric metadata fields (e.g.
    // model latency budget). Silences the unused-import warning.
    @Suppress("unused")
    private fun JsonObject.floatOrNull(key: String): Float? =
        this[key]?.jsonPrimitive?.floatOrNull

    private fun fail(pack: String, msg: String): Nothing =
        throw PackManifestException("Pack '$pack': $msg")
}

class PackManifestException(message: String, cause: Throwable? = null) :
    IllegalArgumentException(message, cause)
