package org.moashraf.sayva.designsystem

/**
 * Sayva renders icons as glyphs in the bundled "Material Symbols Rounded" font
 * rather than as vector ImageVectors - this matches the original design's
 * icon-font approach (`<span class="msr">name</span>`) and keeps the icon set
 * exactly in sync with the design (codepoints sourced directly from Google's
 * material-design-icons metadata).
 */
object MaterialSymbol {
    private val codepoints: Map<String, Int> = mapOf(
        "accessibility_new" to 0xe92c,
        "add" to 0xe145,
        "arrow_back" to 0xe5c4,
        "arrow_forward" to 0xe5c8,
        "auto_awesome" to 0xe65f,
        "auto_fix_high" to 0xe663,
        "back_hand" to 0xe764,
        "battery_full" to 0xe1a5,
        "battery_saver" to 0xefde,
        "bolt" to 0xea0b,
        "bookmark" to 0xe8e7,
        "bookmark_border" to 0xe8e7,
        "bug_report" to 0xe868,
        "cameraswitch" to 0xefeb,
        "cast" to 0xe307,
        "celebration" to 0xea65,
        "check" to 0xe668,
        "check_circle" to 0xf0be,
        "chevron_right" to 0xe5cc,
        "circle" to 0xef4a,
        "cleaning_services" to 0xf0ff,
        "close" to 0xe5cd,
        "cloud" to 0xf15c,
        "cloud_download" to 0xe2c0,
        "cloud_off" to 0xe2c1,
        "cloud_upload" to 0xe2c3,
        "content_copy" to 0xe14d,
        "contrast" to 0xeb37,
        "dark_mode" to 0xe51c,
        "delete" to 0xe92e,
        "delete_outline" to 0xe92e,
        "delete_sweep" to 0xe16c,
        "diversity_3" to 0xf8d9,
        "download" to 0xf090,
        "edit" to 0xf097,
        "emergency" to 0xe1eb,
        "error" to 0xf8b6,
        "expand_more" to 0xe5cf,
        "family_restroom" to 0xf1a2,
        "favorite" to 0xe87e,
        "file_download" to 0xf090,
        "filter_list" to 0xe152,
        "fingerprint" to 0xe90d,
        "format_size" to 0xe245,
        "forum" to 0xe8af,
        "graphic_eq" to 0xe1b8,
        "hd" to 0xe052,
        "help" to 0xe8fd,
        "history" to 0xe8b3,
        "history_toggle_off" to 0xf17d,
        "home" to 0xe9b2,
        "image" to 0xe3f4,
        "info" to 0xe88e,
        "keyboard" to 0xe312,
        "lightbulb" to 0xe90f,
        "lock" to 0xe899,
        "lock_reset" to 0xeade,
        "manage_accounts" to 0xf02e,
        "mark_email_read" to 0xf18c,
        "medical_services" to 0xf109,
        "mic" to 0xe31d,
        "model_training" to 0xf0cf,
        "mood" to 0xea22,
        "more_vert" to 0xe5d4,
        "motion_photos_off" to 0xe9c0,
        "no_photography" to 0xf1a8,
        "notifications" to 0xe7f5,
        "open_in_new" to 0xe89e,
        "palette" to 0xe40a,
        "pause" to 0xe034,
        "person" to 0xf0d3,
        "person_add" to 0xea4d,
        "phone_in_talk" to 0xe61d,
        "pin" to 0xf045,
        "play_arrow" to 0xe037,
        "priority_high" to 0xe645,
        "psychology" to 0xea4a,
        "record_voice_over" to 0xe91f,
        "replay" to 0xe042,
        "restaurant" to 0xe56c,
        "rocket_launch" to 0xeb9b,
        "school" to 0xe80c,
        "screen_record" to 0xf679,
        "search" to 0xef7a,
        "send" to 0xe163,
        "sentiment_dissatisfied" to 0xe811,
        "sentiment_satisfied" to 0xe813,
        "settings" to 0xe8b8,
        "share" to 0xe80d,
        "shield" to 0xe9e0,
        "sign_language" to 0xebe5,
        "signal_cellular_4_bar" to 0xe1c8,
        "slow_motion_video" to 0xe068,
        "smartphone" to 0xe7ba,
        "speed" to 0xe9e4,
        "star" to 0xf09a,
        "star_outline" to 0xf09a,
        "stop_circle" to 0xef71,
        "support_agent" to 0xf0e2,
        "tablet" to 0xe32f,
        "text_increase" to 0xeae2,
        "timer" to 0xe425,
        "tips_and_updates" to 0xe79a,
        "translate" to 0xe8e2,
        "trending_flat" to 0xe8e4,
        "tune" to 0xe429,
        "verified" to 0xef76,
        "verified_user" to 0xf013,
        "vibration" to 0xf2cb,
        "videocam" to 0xe04b,
        "visibility" to 0xe8f4,
        "visibility_off" to 0xe8f5,
        "volume_up" to 0xe050,
        "volunteer_activism" to 0xea70,
        "warning" to 0xf083,
        "warning_amber" to 0xf083,
        "waving_hand" to 0xe766,
        "whatshot" to 0xe80e,
        "wifi" to 0xe63e,
        "workspace_premium" to 0xe7af,
    )

    fun glyph(name: String): String {
        val codepoint = codepoints[name]
            ?: error("Unknown MaterialSymbol icon: $name")
        return codepoint.toChar().toString()
    }
}
