"""Language Pack manifest schema + loader.

The manifest is authored in `manifest.yaml` inside each pack. The distributed
form (`manifest.json`) is generated by `scripts/generate_pack.py` and is what
the mobile app parses.

Every pack — ASL, EgSL, SSL, JSL, BSL, any future language — uses this same
schema. Adding a canonical output language means adding it to every pack's
`supportedOutputs`; the schema itself doesn't change.
"""

from __future__ import annotations

import enum
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

# SemVer 2.0.0 core + optional prerelease / build metadata. Applied to every
# pack's `version` field at parse time so a pack that ships `1.0` (missing
# patch) or an empty string fails fast at build time instead of poisoning
# analytics or breaking runtime version comparisons on-device.
_SEMVER_RE = re.compile(
    r"^"
    r"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"           # MAJOR.MINOR.PATCH
    r"(?:-((?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)"     # -prerelease
    r"(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*))?"
    r"(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?"        # +build
    r"$"
)


def is_valid_semver(value: str) -> bool:
    """Whether `value` matches SemVer 2.0.0.

    Exported so tests + the version-bump-check script can share one regex.
    """
    return bool(_SEMVER_RE.match(value))

from sayva_ml.vocabulary import Vocabulary, load_vocabulary

# Canonical output languages every pack must ship a `labels/{code}.json` for.
# Adding a new one is a coordinated one-time schema change: add it here, add
# stub label files to every existing pack, ship the schema bump. Do not add
# a new output as a per-pack optional field — the whole point is uniformity.
CANONICAL_OUTPUTS: tuple[str, ...] = ("en", "ar")


class OutputLanguageStatus(str, enum.Enum):
    """Translation completeness for one output language in one pack."""

    STUB = "stub"          # File exists so schema passes; entries are placeholders / null
    PARTIAL = "partial"    # Some entries translated, others still null
    COMPLETE = "complete"  # Every vocab entry has a reviewed translation


# Ordering conventions for two-hand model input assembly. Each two-hand pack
# picks one — the recognition pipeline routes MediaPipe detections into the
# model's input slots based on this. Single-hand models (max_hands == 1) leave
# this field unset.
#
# * left_right  — slot 0 = Left hand landmarks, slot 1 = Right (zero-filled
#                 when a hand is missing). Matches the convention most
#                 fingerspelling / two-hand-sign models trained on datasets
#                 that pre-label handedness.
# * right_left  — mirror of the above; some Asian sign language datasets
#                 label dominant-first, which for a majority-right-handed
#                 signer corpus maps to right-first.
# * first_seen  — preserve the detector's emission order. Useful when the
#                 model was trained on unlabeled hand pairs (e.g. WLASL
#                 clips where handedness metadata is inconsistent).
TWO_HAND_ORDERINGS: tuple[str, ...] = ("left_right", "right_left", "first_seen")


@dataclass(frozen=True)
class ModelInputSpec:
    shape: tuple[int, ...]
    preprocessing: str           # Preprocessor adapter ID (registry key on the app side)
    max_hands: int               # 1 or 2 — pipeline uses this to configure HandDetector
    sequence_length: int | None = None
    # Present only when max_hands == 2; validated at parse time. Value is one
    # of TWO_HAND_ORDERINGS. See that constant's docstring for semantics.
    two_hand_ordering: str | None = None


@dataclass(frozen=True)
class ModelOutputSpec:
    shape: tuple[int, ...]
    postprocessing: str          # Postprocessor adapter ID (registry key on the app side)


@dataclass(frozen=True)
class ConfidenceThresholds:
    """Per-model confidence buckets used by the recognition pipeline UI."""
    show: float                  # >= this → render as-is
    caution: float               # >= this and < show → render with caution styling
                                 # < this → route to low-confidence flow


@dataclass(frozen=True)
class ModelSpec:
    id: str
    role: str                    # capability identifier — "fingerspelling", "sign_recognition", ...
    architecture: str            # descriptive metadata — "mlp", "lstm_unrolled", "transformer_v1"
    file: str                    # relative to pack root
    runtime_type: str            # ModelRuntime adapter ID — "tflite", "coreml", "onnx", ...
    inference_strategy: str      # "single_frame", "sliding_window", "streaming_stateful"
    input: ModelInputSpec
    output: ModelOutputSpec
    confidence_thresholds: ConfidenceThresholds
    vocabulary_file: str         # relative to pack root
    vocabulary: Vocabulary       # loaded from vocabulary_file at manifest-parse time


@dataclass(frozen=True)
class PostProcessingRules:
    spell_out_blank_timeout_ms: int
    sentence_assembly_ruleset: str
    capitalization: str


@dataclass(frozen=True)
class LanguagePackManifest:
    schema_version: int
    recognition_code: str
    display_name: dict[str, str]
    version: str                 # SemVer as string
    min_app_version: int
    bundled: bool
    models: tuple[ModelSpec, ...]
    supported_outputs: tuple[str, ...]
    output_language_status: dict[str, OutputLanguageStatus]
    default_output_language: str
    output_labels_dir: str
    tts_locale_by_output: dict[str, str]
    post_processing: PostProcessingRules
    pack_root: Path              # convenience — not serialized to distribution
    output_labels: dict[str, dict[str, dict[str, str | None]]] = field(default_factory=dict)


def _require_key(mapping: dict[str, Any], key: str, source: Path) -> Any:
    if key not in mapping:
        raise ValueError(f"{source}: missing required key '{key}'")
    return mapping[key]


def _parse_model(raw: dict[str, Any], pack_root: Path, source: Path) -> ModelSpec:
    for k in (
        "id", "role", "architecture", "file", "runtime", "inferenceStrategy",
        "input", "output", "confidenceThresholds", "vocabularyFile",
    ):
        _require_key(raw, k, source)

    runtime_raw = raw["runtime"]
    if not isinstance(runtime_raw, dict) or "type" not in runtime_raw:
        raise ValueError(f"{source}: model '{raw['id']}' runtime must have 'type'")
    runtime_type = str(runtime_raw["type"])

    inp = raw["input"]
    for req in ("shape", "preprocessing", "maxHands"):
        if req not in inp:
            raise ValueError(f"{source}: model '{raw['id']}' input must have '{req}'")
    max_hands = int(inp["maxHands"])
    if max_hands not in (1, 2):
        raise ValueError(
            f"{source}: model '{raw['id']}' maxHands must be 1 or 2, got {max_hands}"
        )
    two_hand_ordering_raw = inp.get("twoHandOrdering")
    if max_hands == 2:
        if two_hand_ordering_raw is None:
            raise ValueError(
                f"{source}: model '{raw['id']}' has maxHands=2 and must "
                f"declare 'twoHandOrdering' (one of {TWO_HAND_ORDERINGS})."
            )
        if two_hand_ordering_raw not in TWO_HAND_ORDERINGS:
            raise ValueError(
                f"{source}: model '{raw['id']}' twoHandOrdering "
                f"{two_hand_ordering_raw!r} must be one of {TWO_HAND_ORDERINGS}"
            )
    else:
        if two_hand_ordering_raw is not None:
            raise ValueError(
                f"{source}: model '{raw['id']}' declares 'twoHandOrdering' but "
                f"maxHands={max_hands}; the field is only valid for two-hand models."
            )
    input_spec = ModelInputSpec(
        shape=tuple(int(x) for x in inp["shape"]),
        preprocessing=str(inp["preprocessing"]),
        max_hands=max_hands,
        sequence_length=int(inp["sequenceLength"]) if "sequenceLength" in inp else None,
        two_hand_ordering=two_hand_ordering_raw,
    )

    out = raw["output"]
    if not isinstance(out, dict) or "shape" not in out or "postprocessing" not in out:
        raise ValueError(f"{source}: model '{raw['id']}' output must have shape + postprocessing")
    output_spec = ModelOutputSpec(
        shape=tuple(int(x) for x in out["shape"]),
        postprocessing=str(out["postprocessing"]),
    )

    thresh_raw = raw["confidenceThresholds"]
    for req in ("show", "caution"):
        if req not in thresh_raw:
            raise ValueError(
                f"{source}: model '{raw['id']}' confidenceThresholds must have '{req}'"
            )
    show_t = float(thresh_raw["show"])
    caution_t = float(thresh_raw["caution"])
    if not (0.0 <= caution_t <= show_t <= 1.0):
        raise ValueError(
            f"{source}: model '{raw['id']}' confidenceThresholds must satisfy "
            f"0 <= caution <= show <= 1; got show={show_t}, caution={caution_t}"
        )
    thresholds = ConfidenceThresholds(show=show_t, caution=caution_t)

    vocab_file = str(raw["vocabularyFile"])
    vocab_path = pack_root / vocab_file
    if not vocab_path.exists():
        raise FileNotFoundError(f"{source}: vocabularyFile '{vocab_file}' not found at {vocab_path}")
    vocab = load_vocabulary(vocab_path)

    # Sanity: vocabulary size must match model output class count.
    if output_spec.shape[-1] != vocab.size:
        raise ValueError(
            f"{source}: model '{raw['id']}' output shape {output_spec.shape} "
            f"declares {output_spec.shape[-1]} classes but vocabulary at "
            f"{vocab_file} has {vocab.size} signs — retrain or fix vocabulary.",
        )

    return ModelSpec(
        id=str(raw["id"]),
        role=str(raw["role"]),
        architecture=str(raw["architecture"]),
        file=str(raw["file"]),
        runtime_type=runtime_type,
        inference_strategy=str(raw["inferenceStrategy"]),
        input=input_spec,
        output=output_spec,
        confidence_thresholds=thresholds,
        vocabulary_file=vocab_file,
        vocabulary=vocab,
    )


def _parse_status(raw: dict[str, str], source: Path) -> dict[str, OutputLanguageStatus]:
    out: dict[str, OutputLanguageStatus] = {}
    for code, val in raw.items():
        try:
            out[code] = OutputLanguageStatus(val)
        except ValueError as exc:
            raise ValueError(f"{source}: invalid outputLanguageStatus[{code}] = {val!r}") from exc
    return out


def _load_output_labels(
    pack_root: Path,
    labels_dir: str,
    supported: tuple[str, ...],
    model_ids: tuple[str, ...],
    vocabs_by_model: dict[str, Vocabulary],
) -> dict[str, dict[str, dict[str, str | None]]]:
    """Load one JSON per output language and validate coverage.

    Enforces the uniform contract: every supported output MUST have a labels
    file, and every file MUST include an entry for each of the pack's models.
    Individual sign entries may be `null` (missing translation) — that's what
    the fallback annotation handles at rendering time.
    """
    result: dict[str, dict[str, dict[str, str | None]]] = {}
    labels_root = pack_root / labels_dir
    for code in supported:
        labels_path = labels_root / f"{code}.json"
        if not labels_path.exists():
            raise FileNotFoundError(
                f"Pack labels file missing: {labels_path} — every pack must ship a "
                f"labels/{code}.json (may be a stub with null values)."
            )
        with labels_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        per_model: dict[str, dict[str, str | None]] = {}
        for mid in model_ids:
            if mid not in data:
                raise ValueError(
                    f"Labels file {labels_path} missing entry for model '{mid}'."
                )
            entries = data[mid]
            if not isinstance(entries, dict):
                raise ValueError(
                    f"Labels file {labels_path} model '{mid}' must be an object of sign_id → label"
                )
            # Every sign in the vocab must appear as a key (value can be null).
            vocab = vocabs_by_model[mid]
            vocab_ids = {s.id for s in vocab.signs}
            missing = vocab_ids - set(entries.keys())
            extra = set(entries.keys()) - vocab_ids
            if missing:
                raise ValueError(
                    f"Labels file {labels_path} model '{mid}' missing sign IDs: {sorted(missing)}"
                )
            if extra:
                raise ValueError(
                    f"Labels file {labels_path} model '{mid}' has unknown sign IDs: {sorted(extra)}"
                )
            per_model[mid] = {k: (v if v is None else str(v)) for k, v in entries.items()}
        result[code] = per_model
    return result


def load_manifest(pack_root: Path) -> LanguagePackManifest:
    """Load and validate `packs/{code}/manifest.yaml` + attached vocab + labels.

    Raises `ValueError` / `FileNotFoundError` on any contract violation —
    the manifest passes fully or not at all.
    """
    manifest_path = pack_root / "manifest.yaml"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Pack manifest not found at {manifest_path}")
    with manifest_path.open("r", encoding="utf-8") as f:
        raw: dict[str, Any] = yaml.safe_load(f)
    if not isinstance(raw, dict):
        raise ValueError(f"{manifest_path}: manifest must parse as a mapping")

    for k in (
        "schemaVersion", "recognitionCode", "displayName", "version",
        "minAppVersion", "bundled", "models", "supportedOutputs",
        "outputLanguageStatus", "defaultOutputLanguage", "outputLabelsDir",
        "ttsLocaleByOutput", "postProcessing",
    ):
        _require_key(raw, k, manifest_path)

    supported = tuple(str(x) for x in raw["supportedOutputs"])
    # Enforce the shared canonical-output contract.
    missing_canonical = [c for c in CANONICAL_OUTPUTS if c not in supported]
    if missing_canonical:
        raise ValueError(
            f"{manifest_path}: pack must declare every canonical output "
            f"({CANONICAL_OUTPUTS}); missing {missing_canonical}."
        )

    models = tuple(_parse_model(m, pack_root, manifest_path) for m in raw["models"])
    if not models:
        raise ValueError(f"{manifest_path}: pack must declare at least one model")
    seen_model_ids: set[str] = set()
    seen_roles: set[str] = set()
    for m in models:
        if m.id in seen_model_ids:
            raise ValueError(f"{manifest_path}: duplicate model id '{m.id}'")
        seen_model_ids.add(m.id)
        # One pack, one model per role. Multi-model-per-role (fallbacks,
        # A/B testing) is a future feature — when it lands, this check flips
        # to "at most one primary per role" and a new `priority` field breaks
        # ties. Explicitly rejecting for now surfaces manifest mistakes.
        if m.role in seen_roles:
            raise ValueError(
                f"{manifest_path}: multiple models declare role '{m.role}'. "
                f"One pack, one model per role in this schema version."
            )
        seen_roles.add(m.role)

    status = _parse_status(raw["outputLanguageStatus"], manifest_path)
    missing_status = set(supported) - set(status.keys())
    if missing_status:
        raise ValueError(
            f"{manifest_path}: outputLanguageStatus missing entries for {sorted(missing_status)}"
        )

    default_output = str(raw["defaultOutputLanguage"])
    if default_output not in supported:
        raise ValueError(
            f"{manifest_path}: defaultOutputLanguage '{default_output}' "
            f"not in supportedOutputs {supported}"
        )

    tts_by_output = {str(k): str(v) for k, v in raw["ttsLocaleByOutput"].items()}
    missing_tts = set(supported) - set(tts_by_output.keys())
    if missing_tts:
        raise ValueError(
            f"{manifest_path}: ttsLocaleByOutput missing entries for {sorted(missing_tts)}"
        )

    pp_raw = raw["postProcessing"]
    post = PostProcessingRules(
        spell_out_blank_timeout_ms=int(pp_raw["spellOutBlankTimeoutMs"]),
        sentence_assembly_ruleset=str(pp_raw["sentenceAssemblyRuleset"]),
        capitalization=str(pp_raw["capitalization"]),
    )

    vocabs_by_model = {m.id: m.vocabulary for m in models}
    output_labels = _load_output_labels(
        pack_root=pack_root,
        labels_dir=str(raw["outputLabelsDir"]),
        supported=supported,
        model_ids=tuple(m.id for m in models),
        vocabs_by_model=vocabs_by_model,
    )

    display_name = {str(k): str(v) for k, v in raw["displayName"].items()}
    version_str = str(raw["version"]).strip()
    if not version_str:
        raise ValueError(f"{manifest_path}: 'version' must be a non-empty SemVer string")
    if not is_valid_semver(version_str):
        raise ValueError(
            f"{manifest_path}: 'version' {version_str!r} is not valid SemVer 2.0.0. "
            f"Expected MAJOR.MINOR.PATCH (e.g. '1.0.0' or '0.2.3-beta.1')."
        )
    return LanguagePackManifest(
        schema_version=int(raw["schemaVersion"]),
        recognition_code=str(raw["recognitionCode"]),
        display_name=display_name,
        version=version_str,
        min_app_version=int(raw["minAppVersion"]),
        bundled=bool(raw["bundled"]),
        models=models,
        supported_outputs=supported,
        output_language_status=status,
        default_output_language=default_output,
        output_labels_dir=str(raw["outputLabelsDir"]),
        tts_locale_by_output=tts_by_output,
        post_processing=post,
        pack_root=pack_root,
        output_labels=output_labels,
    )


def validate_pack(pack_root: Path) -> LanguagePackManifest:
    """`load_manifest` + verify every referenced model file exists on disk.

    CI uses this to check every pack in `ml/packs/` before any distribution.
    """
    manifest = load_manifest(pack_root)
    for model in manifest.models:
        model_path = pack_root / model.file
        if not model_path.exists():
            raise FileNotFoundError(
                f"Pack '{manifest.recognition_code}' model '{model.id}' file "
                f"missing at {model_path}"
            )
    return manifest
