package org.moashraf.sayva.ml

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.moashraf.sayva.languagepack.ClasspathPackResourceLoader
import org.moashraf.sayva.languagepack.DefaultLanguagePackRegistry
import org.moashraf.sayva.ml.ArgmaxConfidencePostprocessor
import org.moashraf.sayva.ml.adapters.SingleHandKazuhitoPreprocessor
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlinx.coroutines.runBlocking

/**
 * Kotlin half of the golden-inference contract with the Python side.
 *
 * The shared fixture at `shared/src/androidHostTest/resources/golden_inference.json`
 * is generated by `ml/scripts/generate_golden_inference.py` (which uses real
 * ASL Alphabet images + the trained model). Both this test and its Python
 * counterpart (`ml/tests/test_golden_inference.py`) MUST reproduce the pinned
 * `features_42`, `logits_24`, `top_class_index`, and `top_class_id` from the
 * same inputs — a divergence is a train/serve mismatch.
 *
 * ### What this test does verify (host JVM):
 *  * Preprocessing parity: `SingleHandKazuhitoPreprocessor` (== the
 *    `LandmarkPreprocessor` shared with the Python side) produces the
 *    fixture's `features_42` bit-for-bit when fed the pinned
 *    `raw_landmarks_21`.
 *  * Vocabulary order parity: the active pack's fingerspelling vocabulary
 *    must match `vocab_order` in the fixture, in the same order, so a class
 *    index means the same sign on both platforms.
 *  * Argmax semantics parity: `ArgmaxConfidencePostprocessor` applied to
 *    the fixture's `logits_24` picks the pinned `top_class_index`.
 *
 * ### What this test deliberately does NOT verify:
 *  * The actual TFLite invocation. The `org.tensorflow.lite.Interpreter`
 *    native library isn't available in the JVM host test classpath — every
 *    existing recognizer test uses `FakeModelRuntime`. Running the same
 *    `features_42` through the on-device `.tflite` and asserting logits
 *    match the fixture is a natural follow-up under an
 *    `androidInstrumentedTest` — pending an emulator/device runner.
 *
 * If this host test PASSES but on-device recognition still misclassifies,
 * the mismatch is EITHER in the TFLite runtime (unlikely — deterministic
 * C++ interpreter of the same bytes) OR upstream of preprocessing (camera
 * mirroring, MediaPipe input format, or the landmark pipeline). The static
 * audit points at the front-camera-mirroring case; this test locks the
 * deterministic pieces so that hypothesis is testable.
 */
class GoldenInferenceTest {

    // -----------------------------------------------------------------------

    @Test
    fun `pack vocabulary order matches golden fixture`() = runBlocking<Unit> {
        val (fixture, pack) = load()
        val model = pack.modelById("fingerspelling")
            ?: error("ASE pack has no fingerspelling model")
        val vocabIds = model.vocabulary.signs.map { it.id }
        assertEquals(fixture.vocabOrder, vocabIds,
            "Pack vocabulary order drifted from the golden fixture.")
        assertEquals(model.vocabulary.size, fixture.vocabOrder.size)
    }

    @Test
    fun `preprocess of raw_landmarks_21 matches pinned features_42 on every case`() {
        val fixture = loadFixture()
        for (case in fixture.cases) {
            val flatRaw = FloatArray(42)
            for (i in 0 until 21) {
                flatRaw[i * 2] = case.rawLandmarks21[i][0].toFloat()
                flatRaw[i * 2 + 1] = case.rawLandmarks21[i][1].toFloat()
            }
            val recomputed = SingleHandKazuhitoPreprocessor.preprocess(flatRaw)
            val expected = case.features42
            assertEquals(42, recomputed.size)
            for (i in 0 until 42) {
                val delta = abs(recomputed[i] - expected[i])
                assertTrue(
                    delta <= fixture.toleranceFeatures,
                    "case ${case.signId}: feature[$i] drifted ${recomputed[i]} " +
                        "vs pinned ${expected[i]} (tol ${fixture.toleranceFeatures})",
                )
            }
        }
    }

    @Test
    fun `argmax over pinned logits picks the pinned top_class on every case`() {
        val fixture = loadFixture()
        val vocab = org.moashraf.sayva.languagepack.SignVocabulary(
            version = 1,
            signs = fixture.vocabOrder.mapIndexed { i, id ->
                org.moashraf.sayva.languagepack.VocabSign(
                    index = i, id = id, tags = emptyList(),
                )
            },
        )
        for (case in fixture.cases) {
            val logits = FloatArray(case.logits24.size) { case.logits24[it].toFloat() }
            val result = ArgmaxConfidencePostprocessor.postprocess(logits, vocab)
            assertEquals(
                case.topClassIndex, result.classIndex,
                "case ${case.signId}: Kotlin argmax picked ${result.classIndex} " +
                    "(${vocab.byIndex(result.classIndex)?.id}), pinned was " +
                    "${case.topClassIndex} (${case.topClassId})",
            )
            val sign = vocab.byIndex(result.classIndex)
            assertNotNull(sign)
            assertEquals(case.topClassId, sign.id)
        }
    }

    @Test
    fun `every fixture case reports a non-degenerate feature vector`() {
        // Sanity: catch a fixture regenerated from a zero-input degenerate
        // case (pre_process_landmark returns all zeros when max abs is 0).
        // Zero features would let every test pass trivially.
        val fixture = loadFixture()
        for (case in fixture.cases) {
            val nonZero = case.features42.count { it != 0.0 }
            assertTrue(
                nonZero >= 30,
                "case ${case.signId}: features_42 has only $nonZero non-zero " +
                    "components — likely a degenerate landmark input.",
            )
        }
    }

    // -----------------------------------------------------------------------

    private fun loadFixture(): GoldenFixture {
        val path = "golden_inference.json"
        val stream = javaClass.classLoader?.getResourceAsStream(path)
            ?: error("Golden fixture not on classpath: $path")
        val text = stream.use { it.readBytes().decodeToString() }
        return json.decodeFromString(GoldenFixture.serializer(), text)
    }

    private suspend fun load(): Pair<GoldenFixture, org.moashraf.sayva.languagepack.LanguagePack> {
        val fixture = loadFixture()
        val registry = DefaultLanguagePackRegistry(
            ClasspathPackResourceLoader(listOf(fixture.packCode))
        )
        registry.refresh()
        val pack = registry.byRecognitionCode(fixture.packCode)
            ?: error("Pack '${fixture.packCode}' not found on classpath")
        return fixture to pack
    }

    private companion object {
        val json = Json { ignoreUnknownKeys = true }
    }
}

@Serializable
private data class GoldenFixture(
    val schema_version: Int,
    val pack_code: String,
    val model_version: String,
    val vocab_hash: String,
    val vocab_order: List<String>,
    val tolerance_features: Double,
    val tolerance_logits: Double,
    val cases: List<GoldenCase>,
) {
    val packCode: String get() = pack_code
    val vocabOrder: List<String> get() = vocab_order
    val toleranceFeatures: Double get() = tolerance_features
    val toleranceLogits: Double get() = tolerance_logits
}

@Serializable
private data class GoldenCase(
    val sign_id: String,
    val source_image: String,
    val image_width: Int,
    val image_height: Int,
    val raw_landmarks_21: List<List<Int>>,
    val features_42: List<Double>,
    val logits_24: List<Double>,
    val top_class_index: Int,
    val top_class_id: String,
    val top_softmax: Double,
) {
    val signId: String get() = sign_id
    val rawLandmarks21: List<List<Int>> get() = raw_landmarks_21
    val features42: List<Double> get() = features_42
    val logits24: List<Double> get() = logits_24
    val topClassIndex: Int get() = top_class_index
    val topClassId: String get() = top_class_id
}
