package org.moashraf.sayva.ml

import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Landmark preprocessing parity — Kotlin-side check.
 *
 * Reads the shared fixture generated by
 * `ml/scripts/generate_landmark_fixture.py` (Python-side authoritative
 * expected output) and verifies the Kotlin port produces the same numbers
 * within the recorded tolerance.
 *
 * A failure here means Python and Kotlin have drifted — the on-device model
 * will silently see different inputs than training saw. Fix the drift; do
 * not raise the tolerance.
 */
class LandmarkPreprocessorParityTest {

    @Test
    fun `every fixture case matches within tolerance`() {
        val fixture = loadFixture()
        val cases = fixture.cases
        assertTrue(cases.isNotEmpty(), "Fixture must contain at least one case")
        for (case in cases) {
            val flat = FloatArray(42)
            for (i in 0 until 21) {
                flat[i * 2] = case.raw[i][0]
                flat[i * 2 + 1] = case.raw[i][1]
            }
            val actual = LandmarkPreprocessor.preprocess(flat)
            assertEquals(
                42, actual.size,
                "case '${case.id}': expected 42-float output, got ${actual.size}",
            )
            for (i in actual.indices) {
                val diff = abs(actual[i] - case.expected[i])
                if (diff > fixture.tolerance) {
                    fail(
                        "case '${case.id}' element $i: " +
                            "actual=${actual[i]} expected=${case.expected[i]} " +
                            "diff=$diff tolerance=${fixture.tolerance}",
                    )
                }
            }
        }
    }

    @Test
    fun `degenerate zero-extent input yields all-zeros`() {
        val flat = FloatArray(42) { 100f }
        val out = LandmarkPreprocessor.preprocess(flat)
        assertTrue(out.all { it == 0f }, "Expected zero vector, got ${out.toList()}")
    }

    @Test
    fun `rejects wrong-sized input`() {
        val ex = runCatching { LandmarkPreprocessor.preprocess(FloatArray(40)) }
            .exceptionOrNull()
        assertTrue(
            ex is IllegalArgumentException,
            "Expected IllegalArgumentException, got $ex",
        )
    }

    @Test
    fun `two-hand cases match python fixture`() {
        val fixture = loadFixture()
        for (case in fixture.twoHandCases) {
            val leftFlat = case.left?.let { flatten(it) }
            val rightFlat = case.right?.let { flatten(it) }
            val actual = LandmarkPreprocessor.preprocessTwoHandFrame(leftFlat, rightFlat)
            assertEquals(84, actual.size, "case '${case.id}': expected 84 floats")
            for (i in actual.indices) {
                val diff = abs(actual[i] - case.expected[i])
                if (diff > fixture.tolerance) {
                    fail(
                        "two-hand case '${case.id}' element $i: " +
                            "actual=${actual[i]} expected=${case.expected[i]} " +
                            "diff=$diff tolerance=${fixture.tolerance}"
                    )
                }
            }
        }
    }

    @Test
    fun `sequence cases match python fixture`() {
        val fixture = loadFixture()
        for (case in fixture.sequenceCases) {
            val frames = case.frames.map { (l, r) ->
                (l?.let { flatten(it) }) to (r?.let { flatten(it) })
            }
            val actual = LandmarkPreprocessor.preprocessTwoHandSequence(
                frames = frames,
                targetLength = case.targetLength,
            )
            assertEquals(
                case.targetLength * 84, actual.size,
                "sequence case '${case.id}': expected ${case.targetLength * 84} floats",
            )
            // Expected is [[84 floats] * targetLength]; flatten for compare.
            for (row in 0 until case.targetLength) {
                for (col in 0 until 84) {
                    val a = actual[row * 84 + col]
                    val e = case.expected[row][col]
                    val diff = abs(a - e)
                    if (diff > fixture.tolerance) {
                        fail(
                            "seq case '${case.id}' [$row][$col]: " +
                                "actual=$a expected=$e diff=$diff"
                        )
                    }
                }
            }
        }
    }

    @Test
    fun `two-hand frame with missing hand fills that half with zeros`() {
        val left = FloatArray(42) { it * 5f + 100f }
        val out = LandmarkPreprocessor.preprocessTwoHandFrame(left = left, right = null)
        assertEquals(84, out.size)
        // Left half (indices 0..41) — normalized values, at least one non-zero.
        assertTrue(out.take(42).any { it != 0f })
        // Right half (indices 42..83) — all zeros.
        assertTrue(out.drop(42).all { it == 0f })
    }

    private fun flatten(pairs: List<List<Float>>): FloatArray {
        val out = FloatArray(42)
        for (i in 0 until 21) {
            out[i * 2] = pairs[i][0]
            out[i * 2 + 1] = pairs[i][1]
        }
        return out
    }

    // Minimal JSON reader — kotlinx.serialization is not on the shared
    // module's classpath and adding it just for a test file is overkill.
    // The fixture is a fixed schema; a hand-rolled parser is fine.
    private data class Fixture(
        val tolerance: Float,
        val cases: List<Case>,
        val twoHandCases: List<TwoHandCase>,
        val sequenceCases: List<SequenceCase>,
    )
    private data class Case(
        val id: String,
        val raw: List<FloatArray>,
        val expected: FloatArray,
    )
    private data class TwoHandCase(
        val id: String,
        val left: List<List<Float>>?,
        val right: List<List<Float>>?,
        val expected: FloatArray,
    )
    private data class SequenceCase(
        val id: String,
        val frames: List<Pair<List<List<Float>>?, List<List<Float>>?>>,
        val targetLength: Int,
        // Fixture stores expected as `[T][84]`; hold it that shape.
        val expected: List<FloatArray>,
    )

    private fun loadFixture(): Fixture {
        val stream = javaClass.classLoader!!
            .getResourceAsStream("landmark_parity.json")
            ?: error("landmark_parity.json missing from test classpath")
        val text = stream.bufferedReader(Charsets.UTF_8).use { it.readText() }
        val root = MiniJson(text).readObject()
        val tol = (root["tolerance"] as Number).toFloat()

        @Suppress("UNCHECKED_CAST")
        val casesRaw = root["cases"] as List<Map<String, Any>>
        val cases = casesRaw.map { c ->
            @Suppress("UNCHECKED_CAST")
            val raw = (c["raw"] as List<List<Number>>).map {
                floatArrayOf(it[0].toFloat(), it[1].toFloat())
            }
            @Suppress("UNCHECKED_CAST")
            val exp = (c["expected"] as List<Number>).map { it.toFloat() }.toFloatArray()
            Case(id = c["id"] as String, raw = raw, expected = exp)
        }

        @Suppress("UNCHECKED_CAST")
        val twoHandRaw = root["two_hand_cases"] as List<Map<String, Any?>>
        val twoHandCases = twoHandRaw.map { c ->
            TwoHandCase(
                id = c["id"] as String,
                left = parseHand(c["left"]),
                right = parseHand(c["right"]),
                expected = (c["expected"] as List<Number>).map { it.toFloat() }.toFloatArray(),
            )
        }

        @Suppress("UNCHECKED_CAST")
        val seqRaw = root["sequence_cases"] as List<Map<String, Any?>>
        val sequenceCases = seqRaw.map { c ->
            @Suppress("UNCHECKED_CAST")
            val frames = (c["frames"] as List<Map<String, Any?>>).map { f ->
                parseHand(f["left"]) to parseHand(f["right"])
            }
            @Suppress("UNCHECKED_CAST")
            val expected = (c["expected"] as List<List<Number>>).map { row ->
                row.map { it.toFloat() }.toFloatArray()
            }
            SequenceCase(
                id = c["id"] as String,
                frames = frames,
                targetLength = (c["target_length"] as Number).toInt(),
                expected = expected,
            )
        }

        return Fixture(
            tolerance = tol,
            cases = cases,
            twoHandCases = twoHandCases,
            sequenceCases = sequenceCases,
        )
    }

    @Suppress("UNCHECKED_CAST")
    private fun parseHand(node: Any?): List<List<Float>>? {
        if (node == null) return null
        val outer = node as List<List<Number>>
        return outer.map { pair -> pair.map { it.toFloat() } }
    }
}

/**
 * Minimal recursive-descent JSON parser. Sufficient for the parity fixture:
 * supports objects, arrays, strings, numbers, `true`/`false`/`null`. Not a
 * full spec implementation — do not reuse.
 */
private class MiniJson(private val s: String) {
    private var i = 0

    fun readObject(): Map<String, Any?> {
        skipWs()
        readValue().let {
            @Suppress("UNCHECKED_CAST")
            return it as Map<String, Any?>
        }
    }

    private fun readValue(): Any? {
        skipWs()
        return when (val c = s[i]) {
            '{' -> readMap()
            '[' -> readList()
            '"' -> readString()
            't', 'f' -> readBool()
            'n' -> { expect("null"); null }
            else -> if (c == '-' || c.isDigit()) readNumber()
            else error("Unexpected char '$c' at $i")
        }
    }

    private fun readMap(): Map<String, Any?> {
        expectChar('{')
        val out = LinkedHashMap<String, Any?>()
        skipWs()
        if (peek() == '}') { i++; return out }
        while (true) {
            skipWs()
            val key = readString()
            skipWs(); expectChar(':')
            // Store nulls too — the fixture uses `"left": null` intentionally.
            out[key] = readValue()
            skipWs()
            if (peek() == ',') { i++; continue }
            expectChar('}'); return out
        }
    }

    private fun readList(): List<Any?> {
        expectChar('[')
        val out = mutableListOf<Any?>()
        skipWs()
        if (peek() == ']') { i++; return out }
        while (true) {
            out.add(readValue())
            skipWs()
            if (peek() == ',') { i++; continue }
            expectChar(']'); return out
        }
    }

    private fun readString(): String {
        expectChar('"')
        val sb = StringBuilder()
        while (s[i] != '"') {
            if (s[i] == '\\') {
                i++
                when (val esc = s[i]) {
                    '"', '\\', '/' -> sb.append(esc)
                    'n' -> sb.append('\n'); 't' -> sb.append('\t'); 'r' -> sb.append('\r')
                    else -> error("Unsupported escape \\$esc")
                }
                i++
            } else {
                sb.append(s[i]); i++
            }
        }
        i++ // closing "
        return sb.toString()
    }

    private fun readNumber(): Number {
        val start = i
        if (s[i] == '-') i++
        while (i < s.length && (s[i].isDigit() || s[i] == '.' || s[i] == 'e' || s[i] == 'E' || s[i] == '+' || s[i] == '-')) i++
        val token = s.substring(start, i)
        return if ('.' in token || 'e' in token || 'E' in token) token.toDouble()
        else token.toLong()
    }

    private fun readBool(): Boolean = if (s.startsWith("true", i)) {
        i += 4; true
    } else {
        expect("false"); false
    }

    private fun expect(w: String) {
        require(s.startsWith(w, i)) { "Expected '$w' at $i, found '${s.substring(i, minOf(i + w.length, s.length))}'" }
        i += w.length
    }

    private fun expectChar(c: Char) {
        require(s[i] == c) { "Expected '$c' at $i, found '${s[i]}'" }
        i++
    }

    private fun peek(): Char = s[i]

    private fun skipWs() {
        while (i < s.length && s[i].isWhitespace()) i++
    }
}
